site:
  baseline: Tecnologia nos mínimos detalhes
  baseurl: /
  canonicalurl: true
  date:
    format: j F Y
    timezone: Americas/SP
  description: Blog do podcast Tecnicalidade
  netlify:
    cms:
      path: admin
      version: latest
    identity:
      version: v1
  pagination:
    max: 5
    path: page
  title: Tecnicalidade
theme: hyde
